### ISSUE TITLE
README.md typo

### ISSUE THREAD

**Issue by lukapodlesnik** [CloudNativeJS/cloud-health#1]
Minor README.md typo:
Promises that are created as part of a LivenessCheck and registered using registerReadinessCheck are executed on calls to getStatus(). 

`registerReadinessCheck` should be `registerLivenessCheck`.

**Comment by seabaylea** [comment]
Good spot. Thanks @lukapodlesnik.

Would you be interested in raising a PR for the update, or would you prefer us to fix it?

**Comment by lukapodlesnik** [comment]
I can open a PR. I have it prepared already actually.

**Comment by gdams** [comment]
ping @lukapodlesnik any progress with this?

**Comment by lukapodlesnik** [comment]
Sorry for late feedback. I opened PR.
