### ISSUE TITLE
Coveralls is not working

### ISSUE THREAD

**Issue by andrewhughes101** [CloudNativeJS/cloud-health#21]
Coveralls doesnt seem to be working anymore 

(The link in README.md (https://coveralls.io/github/CloudNaitveJS/cloud-health?branch=master) is no longer working - fixed in #23 )

**Comment by andrewhughes101** [comment]
Fixed in #24

**Comment by andrewhughes101** [comment]
nyc has been updated due to npm severity warnings #34 therefore coveralls has stopped reporting coverage again so reopening

**Comment by BethGriggs** [comment]
Fixed by updating to beta v15 of nyc.
